import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

const helvetica = localFont({
  src: [
    {
      path: "./fonts/helvetica-neue/HelveticaNeueLight.otf",
      weight: "300", // Light weight
      style: "normal",
    },
    {
      path: "./fonts/helvetica-neue/HelveticaNeue-Roman.otf",
      weight: "400", // Regular weight
      style: "normal",
    },
    {
      path: "./fonts/helvetica-neue/HelveticaNeueMedium.otf",
      weight: "500", // Medium weight
      style: "normal",
    },
    {
      path: "./fonts/helvetica-neue/HelveticaNeueBold.otf",
      weight: "700", // Bold weight
      style: "normal",
    },
    {
      path: "./fonts/helvetica-neue/HelveticaNeueHeavy.otf",
      weight: "900", // Black weight
      style: "normal",
    },
  ],
  variable: "--font-helvetica",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helvetica.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
